### ISSUE TITLE
Archaeological artefact spatiotemporal map using QGIS 2.8.1 and time manager

### ISSUE THREAD

**Issue by tonyduky** [anitagraser/TimeManager#113]
So I have been trying to use Time Manager to make a spatiotemporal map of artefacts found on a archaeological site. 

My goal is to show if there is areas on the site wich concentrates artefacts having the same datation and then to show how it is changing in time.

So I have a vector layer based on a .txt containing attributes like this for example.

Artefact	X	Y	Start	end
AP01	4,58677145	51,4113176	9/14/125	1/1/151
AP02	5,757797	51,867497	9/14/113	9/14/121
AP03	5,358157847	51,5144818	9/14/135	9/14/141
AP04	5,6121461	51,8189731	9/14/178	9/14/191
AP05	5,397239881	51,8268731	9/14/115	9/14/121
AP06	5,417791988	48,64782915	9/14/117	9/14/121
AP07	4,351775942	51,85121718	9/14/140	9/14/141
AP08	4,294725228	51,13161321	9/14/140	9/14/145
AP09	5,29187199	51,882138	9/14/120	9/14/160
AP10	5,255894613	51,36854131	9/14/100	9/14/115
AP11	5,335668648	51,7614918	9/14/131	9/14/145
AP12	5,186364179	52,1775577	9/14/110	9/14/131
AP13	5,389889983	51,815941	9/14/121	9/14/145
AP14	5,417541216	51,69736415	9/14/112	9/14/123
everytime I press play or on/off switch i got something like that :

Traceback (most recent call last): File "/Users/Antoine/.qgis2/python/plugins/timemanager/timemanagercontrol.py", line 314, in playAnimation stepFunction() File "/Users/Antoine/.qgis2/python/plugins/timemanager/timemanagercontrol.py", line 353, in stepForward self.timeLayerManager.stepForward() File "/Users/Antoine/.qgis2/python/plugins/timemanager/timelayermanager.py", line 222, in stepForward self.setCurrentTimePosition(self.getCurrentTimePosition() + self.timeFrame()) File "/Users/Antoine/.qgis2/python/plugins/timemanager/timelayermanager.py", line 217, in setCurrentTimePosition self.refreshTimeRestrictions() File "/Users/Antoine/.qgis2/python/plugins/timemanager/timelayermanager.py", line 136, in refreshTimeRestrictions timeLayer.setTimeRestriction(self.getCurrentTimePosition(),self.timeFrame()) File "/Users/Antoine/.qgis2/python/plugins/timemanager/timevectorlayer.py", line 193, in setTimeRestriction self.getDateType(), date_format=self.getTimeFormat(), query_idiom=idiom) File "/Users/Antoine/.qgis2/python/plugins/timemanager/query_builder.py", line 109, in build_query sub1=create_ymd_substring(ioy,iom,iod,from_attr,quote_type='"') # quote type for column File "/Users/Antoine/.qgis2/python/plugins/timemanager/query_builder.py", line 71, in create_ymd_substring ystr = "SUBSTR({}{}{},{},{})".format(q,col,q, ioy+1,ioy+5) if ioy>=0 else None # adding 1 UnicodeEncodeError: 'ascii' codec can't encode character u'\u017d' in position 6: ordinal not in range(128)

I'm new to QGIs so I dont really now what it means...

It would be really interesting if we could manage to make Time Manager work for archaeological use!

Thank you for your help and work

**Comment by carolinux** [comment]
Hello, 
so your data needs some cleaning before loading into Time Manager. Dates like "9/14/100" are not valid, they need to have the zeroes in front of them, ie "09/14/0100". Also it seems you have some strange characters in your txt file which cannot be parsed. All this doesn't have to do with Time Manager.

However, I tried out your dataset and cleaned it, and it turns out there would have been problems even if the dataset was clean and as expected, because I haven't tested TimeManager with dates before year 1000 extensively and there were some bugs. I fixed them in current master ( 429bd3d4068234c45365504a43ef) and this dataset works:
```
Artefact X Y Start end
AP02 5.757797 51.867497 09/14/0113 09/14/0121
AP03 5.358157847 51.5144818 09/14/0135 09/14/0141
AP04 5.6121461 51.8189731 09/14/0178 09/14/0191
AP05 5.397239881 51.8268731 09/14/0115 09/14/0121
AP06 5.417791988 48.64782915 09/14/0117 09/14/0121
AP07 4.351775942 51.85121718 09/14/0140 09/14/0141
AP08 4.294725228 51.13161321 09/14/0140 09/14/0145
AP09 5.29187199 51.882138 09/14/0120 09/14/0160
AP10 5.255894613 51.36854131 09/14/0100 09/14/0115
AP11 5.335668648 51.7614918 09/14/0131 09/14/0145
AP12 5.186364179 52.1775577 09/14/0110 09/14/0131
AP13 5.389889983 51.815941 09/14/0121 09/14/0145
AP14 5.417541216 51.69736415 09/14/0112 09/14/0123
```

**Comment by carolinux** [comment]
Please follow the instructions here:
https://github.com/anitagraser/TimeManager/blob/master/GITHUB.md
To replace the plugin that you have with the newest version

**Comment by tonyduky** [comment]
It works!!

Thanks a lot this very quick fix!
Do you think it would be possible to use negative dates as well? Because I have a lot of data that will have negative datations in their interval like -100 (B.C) until 50 (A.D) for example.

If this could work as well it would be perfect for archeological use :)

Anyway, thanks a lot for your help and work!

**Comment by carolinux** [comment]
No, this is not supported at the moment because of underlying library limitations. Only years after 100 AD are supported. Feel free to make a feature request for it, there have been a couple of people interested in archaelogical applications, so if there's enough interest I can look into supporting this in the future. 

I would just add 1000 to all your years for now as a temporary solution, so that you can look through them.

**Comment by tonyduky** [comment]
okay thank you!

Where should I write the feature request?

**Comment by carolinux** [comment]
You can open a new issue where you state your requirements.
BTW, years from 0 to 100 may work, feel free to try it.
