### ISSUE TITLE
Error on WFS layer: "Could not set substring to"

### ISSUE THREAD

**Issue by IamJeffG** [anitagraser/TimeManager#133]
I've loaded a WFS vector layer into QGIS. One of its attributes is a datetime, so I tried adding setting TimeManager to work on it.  I can add the layer and set the start time attribute in the Settings dialog, but when I hit "OK" on the Settings, TimeManager raises an error dialog, and the following stacktrace in the log:

```
2015-07-06T15:06:45 2   Traceback (most recent call last):
          File ".qgis2/python/plugins/timemanager/timevectorlayer.py", line 72, in __init__
            self.setSubsetString(self.originalSubsetString)
          File ".qgis2/python/plugins/timemanager/timevectorlayer.py", line 243, in setSubsetString
            raise SubstringException("Could not set substring to".format(subsetString))
        SubstringException: Could not set substring to
```

One observation is the lack of `{}` for formatting in that error string.  (However, I did some debugging to find that the `subsetString`  passed to `setSubsetString` is in fact the empty string.)

More critically, TimeManager isn't usable after this error.  To be clear, I'm not positive that it's a result of my using WFS; however TimeManager works fine for a Shapefile layer on the same installation.

**Comment by carolinux** [comment]
Hello,
we never tried to use WFS files with TimeManager. Can you share the url of your WFS layer?

(Note:#132 may be related)

**Comment by carolinux** [comment]
Also what do you mean TimeManager isn't usable after that? What if you delete the layer from TimeManager?

**Comment by carolinux** [comment]
Alright, QGIS does not support the setting of a subset string on WFS layers at this time.

**Comment by IamJeffG** [comment]
TimeManager is usable afterwards, I only meant to say that TimeManager isn't usable with this particular layer.

Ok, so the problem is in setting a new attribute on the layer. I'm not fully clear what this means.  Is this what is meant by "Shapefiles can't be edited directly, while time-managed. This is an OGR limitation. It also exists for any other query you set: You simply can't edit a shapefile whilst a query is set.", from the README? Maybe we could add a note that the plugin requires layers to be editable (which is not necessarily intuitive to a newbie)?

**Comment by carolinux** [comment]
I think it doesnt have to do with that. What we can add to the readme is that WFS layers aren't supported for now.
