### ISSUE TITLE
Endtime is not optional for raster layers

### ISSUE THREAD

**Issue by anitagraser** [anitagraser/TimeManager#139]
While the GUI suggests that the end time is optional, TimeManager throws the following error if no end time is specified:

```An error occured while trying to add layer clouds2014-01-02 to TimeManager. Cause: You specified that the format of  is %Y-%m-%d, but this did not succeed. Please check againTraceback (most recent call last):
			  File "C:/Users/Anita/.qgis2/python/plugins\timemanager\timemanagercontrol.py", line 607, in createTimeLayerFromRow
			    timeLayer = TimeLayerFactory.get_timelayer_class_from_settings(settings)(settings, self.iface)
			  File "C:/Users/Anita/.qgis2/python/plugins\timemanager\timerasterlayer.py", line 26, in __init__
			    self.getTimeExtents()
			  File "C:/Users/Anita/.qgis2/python/plugins\timemanager\timerasterlayer.py", line 53, in getTimeExtents
			    endTime = str_to_datetime(endStr, self.getTimeFormat())
			  File "C:/Users/Anita/.qgis2/python/plugins\timemanager\time_util.py", line 337, in str_to_datetime
			    raise UnsupportedFormatException(createNiceMessage(datetimeString, specified_fmt, is_archaelogical(),e))
			UnsupportedFormatException: You specified that the format of  is %Y-%m-%d, but this did not succeed. Please check again```

**Comment by carolinux** [comment]
hm actually not sure if this fixes it, do we want accumulation of features?

**Comment by anitagraser** [comment]
Imho, accumulation should not be the default.

**Comment by carolinux** [comment]
yeah, but what should be the behavior when no end time is specified? right now, after the fix, when no end time is specified, endtime=starttime

**Comment by anitagraser** [comment]
endtime=starttime is fine. works for me if I try it with the cloud NetCDF layers

**Comment by carolinux** [comment]
alright, then I leave it like this for now.
Accumulation of rasters would need some more modifications. Let's make a new issue if we ever need that.
