### ISSUE TITLE
OGR_DATETIME_FORMAT

### ISSUE THREAD

**Issue by Redoute** [anitagraser/TimeManager#159]
Shouldn't it be `"%Y/%m/%d %H:%M:%S"` instead of `"%Y-%m-%dT%H:%M:%S"`?
At least the slashes form lets TimeManager create working filter expressions for GPX timestamps. But I am not sure about this.

**Comment by anitagraser** [comment]
No. "%Y-%m-%dT%H:%M:%S" is the proper way https://xkcd.com/1179/

**Comment by Redoute** [comment]
> Or do you mean that GPX files currently cannot be used in Time Manager?

When I select a GPX layer and it's time field with time format "WILL BE INFERRED", then time format will be set to `%Y-%m-%dT%H:%M:%S` and the filter expression will be something like `cast("time" as character) < '2015-12-10T09:48:03' AND cast("time" as character) >= '2015-12-10T09:47:03' `. This doesn't show any points because OGR time format is like `2015/12/10 09:47:03+00` (see `ogrinfo some_file.gpx track_points`).

When changing OGR_DATETIME_FORMAT in time_util.py, then the filter expression is `cast("time" as character) < '2015/12/10 09:48:03' AND cast("time" as character) >= '2015/12/10 09:47:03' `.

**Comment by carolinux** [comment]
I think this means the format can vary, because I have definitely seen the format with the T in the wild.

**Comment by Redoute** [comment]
The T format is used in QGIS attribute table, and the format in the GPX file itself is quite similar. But I don't think OGR SQL uses it.

**Comment by Redoute** [comment]
Here are some observations regarding different data sources, won't make you happy :-( :

QGIS Provider ogr, OGR driver ESRI Shapefile, dialect OGR
Date/QDate works:
cast("fdate" as character) < '2016/02/23' AND cast("fdate" as character) >= '2016/02/20'
QDateTime and QTime not applicable

QGIS Provider ogr, OGR driver GPX, Layer track_points, waypoints or route_points, dialect OGR
DateTime/QDateTime don't work by default (no features selected):
cast("time" as character) < '2015-12-31T23:57:27' AND cast("time" as character) >= '2015-12-31T23:57:07'
Have layers, but animation not possible
DateTime/QDateTime works with time format "%Y/%m/%d %H:%M:%S":
cast("time" as character) < '2015/12/31 23:57:47' AND cast("time" as character) >= '2015/12/31 23:57:27' 
QDate and QTime not applicable (QGIS/OGR allow to create fields as "extension", but later detect them as QString)
As far as I see in OGR the string representation of times is not documented. In source code there are several format strings with slashes in different places, e. g. in swq.cpp ("SQL WHERE expressions"). The name OGR_DATETIME_FORMAT for a dash/T format is definitely misleading, but perhaps OGR could and should be changed to support it.

QGIS Provider gpx, no filter/subset
not applicable, no time fields

QGIS Provider memory, dialect QGIS Expression
datetime/QDateTime, date/QDate and time/QTime don't work:
"Could not match value PyQt4.QtCore.QDateTime(2016, 1, 1, 0, 1, 7) with any of the supported formats. Tried ['%Y-%m-%d %H:%M:%S.%f', ..."
With manual time format "%Y-%m-%dT%H:%M:%S":
'You specified that the format of PyQt4.QtCore.QDateTime(2016, 1, 1, 0, 1, 7) is %Y-%m-%dT%H:%M:%S, but this did not succeed.'
With manual time format "PyQt4.QtCore.QDateTime(%Y, %m, %d, %H, %M, %S)" (no features selected):
"time" < 'PyQt4.QtCore.QDateTime(2015, 12, 31, 23, 59, 27)' AND "time" >= 'PyQt4.QtCore.QDateTime(2015, 12, 31, 23, 59, 07)'
Have layers, but animation not possible
Reason: QgsVectorDataProvider.minimumValue() returns value as string, no override by QgsMemoryProvider

QGIS Provider ogr, OGR driver GPKG, dialect SQLite
DateTime/QDateTime works (but uses idiom OGR):
cast("time" as character) < '2016-01-01T00:01:27' AND cast("time" as character) >= '2016-01-01T00:01:07'
Date/QDate don't work by default (no features selected):
cast("fdate" as character) < '2016/02/20' AND cast("fdate" as character) >= '2016/02/20' 
Date/QDate works with time format "%Y-%m-%d" (but uses idiom OGR):
cast("fdate" as character) < '2016-03-27' AND cast("fdate" as character) >= '2016-03-24'
Time/QTime don't work:
"Could not match value PyQt4.QtCore.QTime(23, 57, 47) with any of the supported formats. Tried [..."
With manual time formats:
'You specified that the format of PyQt4.QtCore.QTime(23, 57, 47) is %H:%M:%S, but this did not succeed."
'Could not parse any dates while trying to get time extents.None of the values (for example PyQt4.QtCore.QTime(23, 57, 47)) matches the format PyQt4.QtCore.QTime(%H, %M, %S)'
I think GeoPackage detects time fields via SQLite's table definition and enforces ISO-8601 strings. Users of SQLite/SpatiaLite without GeoPackage are free to store times in various string formats. For comparable time values you would need to use functions strftime() or datetime() etc. I see there is both a SpatiaLite QGIS Provider and a SQLite/SpatiaLite OGR driver.

QGIS Provider postgres/PostgreSQL database with PostGIS extension, dialect PostGIS
timestamp/QDateTime, date/QDate and time/QTime don't work (idiom OGR, no features selected):
cast("time" as character) < '2015-12-31T23:59:07' AND cast("time" as character) >= '2015-12-31T23:58:47'
cast("fdate" as character) < '2016/03/06' AND cast("fdate" as character) >= '2016/03/03'
Reason: cast as character returns first char "2".
time/QTime don't work:
"Could not match value PyQt4.QtCore.QTime(13, 1, 7) with any of the supported formats."

Proposal:
- configuration of QGIS internal representation should be separated from configuration of filter expression
- for QDate/QTime/QDateTime fields there is no reasonable format configuration
- configuration of filter expression has to be more general, regarding different syntax, casting and behavior
- with this help, users like me should be able to find a working setup
- then optionally default configuration for various cases could be enhanced

**Comment by carolinux** [comment]
Okay, seems like the QDate/Times are a bit of a mess. QDate support was kind of an afterthought anyway. I don't know if I will get the time to do a major overhaul but one thing I can look at  within a reasonable time frame is to make it possible to specify the format without errors, ie, get rid of the:
"You specified that the format of PyQt4.QtCore.QTime(23, 57, 47) is %H:%M:%S, but this did not succeed."

**Comment by anitagraser** [comment]
This seems to be related ...
http://gis.stackexchange.com/questions/188181/qgis-time-manager-having-trouble-parsing-valid-dates

I'm tempted to abandon format guessing and have the user specify the format ...

**Comment by carolinux** [comment]
@Redoute can you email me a sample file to check against? carolinegr@gmail.com
I agree with you @anitagraser , for qdates the user should specify the format. Although still, the dates may be shown differently in QGIS, than the format required for the query (which is the format we actually want). I think it might be easier to just ask people to convert the dates to text and just improve the error message #158

**Comment by craigmcg** [comment]
By the way, in http://gis.stackexchange.com/questions/188181/qgis-time-manager-having-trouble-parsing-valid-dates, the field holding the date is a qText field as noted in the edited question.
![qtext](https://cloud.githubusercontent.com/assets/11298030/14297347/483bf2d2-fb4c-11e5-8d59-53a89e1b9352.png)

**Comment by craigmcg** [comment]
Here is a subset of the dataset I am working on.

[LHP.sqlite.zip](https://github.com/anitagraser/TimeManager/files/206261/LHP.sqlite.zip)

**Comment by carolinux** [comment]
@craigmcg this works for me.
Try adding the .sqlite file as a vector layer and not as a spatialite layer.

**Comment by carolinux** [comment]
@craigmcg Video of me using the dataset:
https://www.youtube.com/watch?v=Y1lfQeQ5C-8&feature=youtu.be

**Comment by craigmcg** [comment]
I watched the video.  Here is a sequence of screens from my workflow (hopefully they are not too small).  Obviously we are running on different platforms and I noticed different encodings, but everything else seemed identical.

Thanks for all the attention you are giving to this.  Let me know if there is anything else I can do.

Select the sqlite file:




Layer imported:



Select layer in Time manager:





Error message:

**Comment by carolinux** [comment]
I can't see the pictures here for some reason. Are you sure you have a latest version?

**Comment by craigmcg** [comment]
I am running QGIS 2.14.0, and I am not sure what version of time manager, when I go to the plugin manager, doesn’t seem to think any plugins need updates.  I discovered a tool for making screen movies, but the movie file is 29 mb and your mail service already rejected a smaller file I tried to send.  If there is a place I can upload it, let me know.

Also here is a subset of the log:

2016-04-06T09:00:01	1	Unparseable value 2012-10-01 in layer LHP lhp MultiPolygon ignored. Cause You specified that the format of 2012-10-01 is %Y/%m/%d, but this did not succeed. Please check again
2016-04-06T09:00:01	1	Unparseable value 2012-11-01 in layer LHP lhp MultiPolygon ignored. Cause You specified that the format of 2012-11-01 is %Y/%m/%d, but this did not succeed. Please check again
2016-04-06T09:00:01	1	Unparseable value 2012-12-01 in layer LHP lhp MultiPolygon ignored. Cause You specified that the format of 2012-12-01 is %Y/%m/%d, but this did not succeed. Please check again
2016-04-06T09:00:01	1	Unparseable value 2013-01-01 in layer LHP lhp MultiPolygon ignored. Cause You specified that the format of 2013-01-01 is %Y/%m/%d, but this did not succeed. Please check again
2016-04-06T09:00:01	1	Unparseable value 2013-02-01 in layer LHP lhp MultiPolygon ignored. Cause You specified that the format of 2013-02-01 is %Y/%m/%d, but this did not succeed. Please check again
2016-04-06T09:00:01	1	Unparseable value 2013-03-01 in layer LHP lhp MultiPolygon ignored. Cause You specified that the format of 2013-03-01 is %Y/%m/%d, but this did not succeed. Please check again
2016-04-06T09:00:01	1	Unparseable value 2013-04-01 in layer LHP lhp MultiPolygon ignored. Cause You specified that the format of 2013-04-01 is %Y/%m/%d, but this did not succeed. Please check again
2016-04-06T09:00:01	1	Unparseable value 2013-05-01 in layer LHP lhp MultiPolygon ignored. Cause You specified that the format of 2013-05-01 is %Y/%m/%d, but this did not succeed. Please check again
2016-04-06T09:00:01	1	Unparseable value 2013-06-01 in layer LHP lhp MultiPolygon ignored. Cause You specified that the format of 2013-06-01 is %Y/%m/%d, but this did not succeed. Please check again
2016-04-06T09:00:01	1	Unparseable value 2013-07-01 in layer LHP lhp MultiPolygon ignored. Cause You specified that the format of 2013-07-01 is %Y/%m/%d, but this did not succeed. Please check again
2016-04-06T09:00:01	1	Unparseable value 2013-08-01 in layer LHP lhp MultiPolygon ignored. Cause You specified that the format of 2013-08-01 is %Y/%m/%d, but this did not succeed. Please check again
2016-04-06T09:00:01	1	Unparseable value 2013-09-01 in layer LHP lhp MultiPolygon ignored. Cause You specified that the format of 2013-09-01 is %Y/%m/%d, but this did not succeed. Please check again
2016-04-06T09:00:01	1	Unparseable value 2013-10-01 in layer LHP lhp MultiPolygon ignored. Cause You specified that the format of 2013-10-01 is %Y/%m/%d, but this did not succeed. Please check again
2016-04-06T09:00:01	1	Unparseable value 2013-11-01 in layer LHP lhp MultiPolygon ignored. Cause You specified that the format of 2013-11-01 is %Y/%m/%d, but this did not succeed. Please check again
2016-04-06T09:00:01	1	Unparseable value 2013-12-01 in layer LHP lhp MultiPolygon ignored. Cause You specified that the format of 2013-12-01 is %Y/%m/%d, but this did not succeed. Please check again
2016-04-06T09:00:01	1	Unparseable value 2014-07-01 in layer LHP lhp MultiPolygon ignored. Cause You specified that the format of 2014-07-01 is %Y/%m/%d, but this did not succeed. Please check again
2016-04-06T09:00:01	2	Traceback (most recent call last):
File "/Users/Craig/.qgis2/python/plugins/timemanager/timevectorlayer.py", line 96, in __init__
extents = self.getTimeExtents()
File "/Users/Craig/.qgis2/python/plugins/timemanager/timevectorlayer.py", line 204, in getTimeExtents
start_str, end_str = self.getMinMaxValues()
File "/Users/Craig/.qgis2/python/plugins/timemanager/timevectorlayer.py", line 183, in getMinMaxValues
.format(uniques[-1], fmt))
Exception: Could not parse any dates while trying to get time extents.None of the values (for example 2014-07-01) matches the format %Y/%m/%d
2016-04-06T09:00:01	2	An error occured while trying to add layer LHP lhp MultiPolygon to TimeManager. Cause: Exception('Could not parse any dates while trying to get time extents.None of the values (for example 2014-07-01) matches the format %Y/%m/%d',)Traceback (most recent call last):
File "/Users/Craig/.qgis2/python/plugins/timemanager/timemanagercontrol.py", line 627, in createTimeLayerFromRow
self.iface)
File "/Users/Craig/.qgis2/python/plugins/timemanager/timevectorlayer.py", line 100, in __init__
raise InvalidTimeLayerError(e)
InvalidTimeLayerError: Exception('Could not parse any dates while trying to get time extents.None of the values (for example 2014-07-01) matches the format %Y/%m/%d',)

**Comment by carolinux** [comment]
Do you maybe have some values in the beginning that have the format Y/m/d?
You can also try explictily setting the format to %Y-%m-%d when you add the layer

**Comment by craigmcg** [comment]
I looked in the attribute table, all the dates are in YYYY-MM-DD format.

I tried both YYYY-MM-DD and yyyy-mm-dd and got the same result.  Just now I also typed in %Y-%m-%d, same result.

Could be a Mac thing?

**Comment by carolinux** [comment]
I don't know, if you can edit time_util.py 
and change:
OGR_DATE_FORMAT
to be
OGR_DATE_FORMAT="%Y-%m-%d"

as a temporary solution, and it works,  then we know that for some reason your dates are seen as qdates by qgis.

**Comment by carolinux** [comment]
time_util.py should be somewhere in
~/.qgis2/python/plugins/timemanager

not sure of the exact location in Mac, but maybe you can search via filename.

**Comment by craigmcg** [comment]
I went into that file and made the change, quit and restarted QGIS, but no change in behavior.

**Comment by craigmcg** [comment]
Ok well for now, my work around is to save that layer as a Shapefile, where it works just as expected.  Let me know if there is anything else I can do to help.

**Comment by carolinux** [comment]
Alright, glad you found a work-around. I gotta say, even though we didn't
find the error exactly, this troubleshooting process gave me some good
feedback to improve logging and error messages.

**Comment by carolinux** [comment]
@Redoute, so you can in fact set the format manually within the UI, it's just the process requires two steps and is hence not very straightforward . I think I can add it as part of the initial add vector form (as an optional, force format thingey). What do you think @anitagraser ?

In the meantime, this is how you can do it in the existing version (I used your GPX file): 

https://www.youtube.com/watch?v=yZhzrT8W7lE&feature=youtu.be

The funny thing is that the dates have the T format when viewed in the attribute table.

**Comment by anitagraser** [comment]
>  I think I can add it as part of the initial add vector form (as an optional, force format thingey). 

+1 I think that will be much more intuitive than the current situation.

**Comment by carolinux** [comment]
@Redoute please tell me if this solved your problem for now though.

**Comment by Redoute** [comment]
@carolinux
Sorry, I couldn't answer earlier.
> so you can in fact set the format manually within the UI, it's just the process requires two steps and is hence not very straightforward

Yes, I thought this is clear. I meant it when I wrote
> DateTime/QDateTime works with time format "%Y/%m/%d %H:%M:%S"

My initial bug report was about:
- TimeManager has an identifier named OGR_DATETIME_FORMAT
- this format is used in filter/subset expressions
- OGR SQL don't understand this format

Later I discovered
- filter/subset expressions are provider specific, and in case of OGR provider for most but not all drivers it is OGR SQL
- Although TimeManager tries two dialects/idioms, it doesn't detect  which provider/driver uses which format for date/time literals
- TimeManager tries the OGR idiom (cast as character) first and it is accepted by other providers/drivers as OGR/OGR, but at least in the PostGIS case it is not appropriate

The observations I posted on sunday showed an additional problem:
- in `TimeVectorLayer.__init__`
- when field type is QTime or
- when field type is QDateTime/QDate, but `getRawMinValue` returns string
  (this happens for memory provider)
  - when timeFormat is PENDING
    `determine_format` is called, which calls `time_util.get_format_of_timeval`,
    which tries `strptime` on the Q-Type
  - else `findValidValues` is called, which calls `str_to_datetime` with the Q-Type, which expects string

> The funny thing is that the dates have the T format when viewed in the attribute table.

Because the providers convert the different time sources in QDateTime/QDate/QTime, so QGIS-internal they are the same. That makes the difference between time formats and strings.

**Comment by carolinux** [comment]
I think when I had tried it, the OGR idiom failed for Postgres layers and then the SQL idiom was tried.

Anyway, I don't really understand the last part - when we have QDates, in initializing the timevector layer, what is the problem you saw? If minimumValue returns a string, I don't see how Time Manager can detect that it's in fact a QDate.

**Comment by Redoute** [comment]
> f minimumValue returns a string, I don't see how Time Manager can detect that it's in fact a QDate. 
It gets QDates from `dataProvider.uniqueValues`.
Sorry, I think I was wrong about `determine_format`. I will edit my last post.

**Comment by rduivenvoorde** [comment]
Moving from https://github.com/anitagraser/TimeManager/issues/180 to here:

@carolinux , I had small chat with @rouault on IRC. His conclusion first was: 

> OGR (wrongly) interprets character as varchar

So I think that depending on the provider a where clause/query like:
`cast("bouwdate" as character) > '1980-01-01 01:00:00' AND cast("bouwdate" as character) < '1983-01-01T01:00:00'`
will work in for example csv provider.
But with Postgis, casting a 'datetime' (which ends up as a 'QDateTime' in QGIS) to character results in exactly 1 (one) character, instead of the expected "1980-01-01T01:00:00"

IF I change 
https://github.com/anitagraser/TimeManager/blob/master/query_builder.py#L9
`STRINGCAST_FORMAT = 'cast("{}" as character) {} \'{}\' AND cast("{}" as character) >= \'{}\' '`
to
 `STRINGCAST_FORMAT = 'cast("{}" as text) {} \'{}\' AND cast("{}" as text) >= \'{}\' '`
it works (for postgis!!).

I think the 'filter-query' is sent straight to the provider, so in this case it works, but for example for other providers it possibly fails?

BUT some further talking to @rouault: it appears that the 'default' width of the casting to character is 1!
And some providers truncate after the cast, and some don't.
The good news it that chaging the STRINGCAST to:
`STRINGCAST_FORMAT = 'cast("{}" as character(100)) {} \'{}\' AND cast("{}" as character(100)) >= \'{}\' '`
fixes my problem because then postgis returns the full date as string and the string comp. (the 100-number is just random, not sure what the maximum width of a DateTime to string is....)

Happy to do a pull request for that? Can I run tests to see if other providers break in this case?

**Comment by carolinux** [comment]
ah, alright if that fixes it and there's no error when the string is
smaller than 100, a quick PR would be great! Put the 100 in the config.py
with a comment so that we don't have magic numbers without explanations
(and instead have magic numbers, with explanations :D )

**Comment by rduivenvoorde** [comment]
Will do as you ask.

I see there is a test for postgres already, wondering why that works....
How do you normally run the tests?

**Comment by carolinux** [comment]
You can see here how I run the tests + the test environment required (tests
are run automatically at every PR):
https://github.com/anitagraser/TimeManager/blob/master/.travis.yml

Now, my guess as to why that thing works is how the layer is added in qgis
- it's added as the 'postgres' type. But if you can make a test that fails
and is then subsequently fixed by the adding of the substring, that would
be ofc fantastic.

**Comment by rduivenvoorde** [comment]
@carolinux I fail to run nosetest due to:
AttributeError: 'module' object has no attribute 'getLogger'
which (for what I have found) is because there is a logging.pyfile in the path already instead of pythons own logging module?
Any idea why you can run tests and I don't?

**Comment by carolinux** [comment]
It probably depends on where/how nose looks first to get the Python modules. I will just rename the module. When #181 passes the tests I will merge into master and you can merge it in.

**Comment by rduivenvoorde** [comment]
did that locally here too, then I get:
ValueError: API 'QDate' has already been set to version 1
which you apparently hit also :-(
Though that may be related to being on Debian testing?

**Comment by carolinux** [comment]
No, I don't think I get that, actually.

**Comment by carolinux** [comment]
OK, so this worked now on the test server. Maybe it's a qt version issue, as you can see in the travis configuration, I use qt-4

**Comment by carolinux** [comment]
@rduivenvoorde  If it's hard to get the test environment set up, you can just open a [WIP] PR and see what Travis says.
OR you can do the following:
```
sip.setapi(u'QDate', 2) 
```
In all the places in the code where I do:
```
sip.setapi('QString', 2)
```
these things are to be found only in the test folder.

**Comment by rduivenvoorde** [comment]
Ghee... finally bingo!!!

All green dots!!

![selection_035](https://cloud.githubusercontent.com/assets/731673/16540053/7b07162a-4056-11e6-89b0-c603ef4ef7d9.png)

The crux:

- add 
```
import sip

sip.setapi('QString', 2)
sip.setapi('QDate', 2)
sip.setapi('QDateTime', 2)
sip.setapi('QTextStream', 2)
sip.setapi('QTime', 2)
sip.setapi('QUrl', 2)
sip.setapi('QVariant', 2)
```
To `__init__.py` of test

And change the startup of QApplication to the new version working with new AuthenticationFramework (see: https://hub.qgis.org/issues/13494)

And last: if QgsApplication is constructed in setUp it is NOT available anymore in the tests... So you need to create them as members: `self.qgs = QgsApplication(sys.argv, False)`

I will do a PR to see if this also builds in current Travis Setup. 
Does that run all tests automatically?

And I will add tests for the cast(character)-change..

**Comment by carolinux** [comment]
Yeah, every PR is built on travis

**Comment by rduivenvoorde** [comment]
> QGIS Provider postgres/PostgreSQL database with PostGIS extension, dialect PostGIS
> timestamp/QDateTime, date/QDate and time/QTime don't work (idiom OGR, no features selected):
> cast("time" as character) < '2015-12-31T23:59:07' AND cast("time" as character) >= '2015-12-31T23:58:47'
> cast("fdate" as character) < '2016/03/06' AND cast("fdate" as character) >= '2016/03/03'
> Reason: cast as character returns first char "2".

That is a ogr-issue, which has a default 'character'-length of 1. Changing  the STRINGCAST template to:
`STRINGCAST_FORMAT = 'cast("{}" as character(50)) {} \'{}\' AND cast("{}" as character(50)) >= \'{}\' '`
fixes that.

> time/QTime don't work:
> "Could not match value PyQt4.QtCore.QTime(13, 1, 7) with any of the supported formats."

I think this is different, but have to dive into this deeper. May have something to do with 
https://github.com/anitagraser/TimeManager/blob/master/time_util.py#L60
DateTypes does not have a 'DateAsQTime'?

Then the only ogr/postgres issue open is I think is the fact that Postgres does not use a 'T' as date/time separator if you cast/output the date to string, see:
https://www.postgresql.org/docs/current/static/datatype-datetime.html
and then especially this part:
> Note: ISO 8601 specifies the use of uppercase letter T to separate the date and time. PostgreSQL accepts that format on input, but on output it uses a space rather than T, as shown above. This is for readability and for consistency with RFC 3339 as well as some other database systems.

And I did not hit this earlier because I had datetime data, BUT the actual data was not within hours extend but in days. So the 'stringcompare' was done on the part before the T. Running the test, which have data with seconds as timeframes, you hit the difference between ' ' and 'T'...

To handle a postgresql layer with DateTime column, we really need to have a second format without the 'T' in it.. or a more finegrained 'guessing' based on actual (OGR)-driver type (though I think Postgresql is the only strange case...). 
@rouault also told me that the different ogr-drivers handle the cast-to-char differently: some of them truncate the string, if you `cast(x as character), while others keep the full string (actually handle it like a varchar/text). But that would be/is fixed by giving the cast a character array length...

**Comment by wondie** [comment]
I think changing the type from QDate to text makes it difficult to save it to database. I was able to save QDate and QDateTime from the qgis custom widgets with no problem; of course  after few days of work :D  

In my view, it is better to add a function that can set data type. It could even be an extra parameter with setWidgetType. But keeping the default is also good for comparability to older codes.

**Comment by anitagraser** [comment]
Note to self: Avoid date columns in PG, use timestamp instead!

**Comment by axelande** [comment]
I have used TimeManager before and really like however I have som problem now with QGIS 2.18.4 (Cant pinpoint the problem to 2.18.4) 

However, I use a postgres/postgis layer as input 
![image](https://cloud.githubusercontent.com/assets/25315785/23541857/40fc0aae-ffea-11e6-9b9a-cc5787e8c708.png)

I've tried to cast the time to time zone with/without time zone. Qgis recognice the type:
![image](https://cloud.githubusercontent.com/assets/25315785/23541766/ba7c3ac6-ffe9-11e6-826a-a166302cb51a.png)
Timemanager manage to get the time aswell:
![image](https://cloud.githubusercontent.com/assets/25315785/23541801/f652cb50-ffe9-11e6-9d63-b4a76554f1c8.png)
But I got the error "Have layers, but animation not possible"

Any suggestion what I shall change?
