### ISSUE TITLE
Error in 3.0 when exporting frames

### ISSUE THREAD

**Issue by tjukanovt** [anitagraser/TimeManager#250]
I did first tests with Time Manager in QGIS 3.0, but when trying to export frames (export frames --> select output folder) I get an error with the following message:

> TypeError: isinstance() arg 2 must be a type or tuple of types 
Traceback (most recent call last):
  File "C:/Users/topit/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\timemanager\timemanagerguicontrol.py", line 221, in selectAnimationFolder
    prev_directory = TimeManagerProjectHandler.plugin_setting(conf.LAST_ANIMATION_PATH_TAG)
  File "C:/Users/topit/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\timemanager\timemanagerprojecthandler.py", line 32, in plugin_setting
    if isinstance(val, QPyNullVariant):
TypeError: isinstance() arg 2 must be a type or tuple of types

Python version: 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)] 
QGIS version: 3.0.1-Girona Girona, a86bec25eb

**Comment by anitagraser** [comment]
Thank you! Please try TimeManager 3.0.1 http://plugins.qgis.org/plugins/timemanager/version/3.0.1/
