### ISSUE TITLE
AttributeError with raster layers "object has no attribute 'resetSubsetString' "

### ISSUE THREAD

**Issue by aaschwanden** [anitagraser/TimeManager#256]
Hi,

using QGIS3, I added a 4 raster layers from the same time-dependent netCDF file to the TimeManager. Now, whenever I click on "Settings", or reload the project, I get the error below:

```
AttributeError: 'CDFRasterLayer' object has no attribute 'resetSubsetString' 
Traceback (most recent call last):
  File "/Users/andy/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/timemanager/timemanagercontrol.py", line 271, in showOptionsDialog
    self.loopAnimation)
  File "/Users/andy/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/timemanager/timemanagerguicontrol.py", line 394, in showOptionsDialog
    settings = layer_settings.getSettingsFromLayer(layer)
  File "/Users/andy/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/timemanager/layer_settings.py", line 184, in getSettingsFromLayer
    result.resetSubsetString = layer.resetSubsetString()
AttributeError: 'CDFRasterLayer' object has no attribute 'resetSubsetString'
```

The netCDF file is about 55Gb compressed (>150Gb uncompressed), but I can cut out a small area as a test case, if needed.

Thanks, Andy

**Comment by merkato** [comment]
Same issue #257

**Comment by anitagraser** [comment]
Thank you for reporting this issue. Unfortunately, I currently don't have time to fix this. I'll get to it when I can.
