### ISSUE TITLE
QGIS3 MacOSX: Python error

### ISSUE THREAD

**Issue by soester** [anitagraser/TimeManager#258]
When triing to enable timemanager in QGIS 3.2 on MacOSX the following errors occur:
```
Couldn't load plugin 'timemanager' due to an error when calling its classFactory() method 

ModuleNotFoundError: No module named 'future' 
Traceback (most recent call last):
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 337, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/Users/imac5k/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/timemanager/__init__.py", line 15, in classFactory
    from .timemanager import timemanager
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 665, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/imac5k/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/timemanager/timemanager.py", line 26, in 
    from .timemanagercontrol import TimeManagerControl
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 665, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/imac5k/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/timemanager/timemanagercontrol.py", line 19, in 
    from .timemanagerguicontrol import TimeManagerGuiControl, MAX_TIME_LENGTH_SECONDS_SLIDER
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 665, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/imac5k/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/timemanager/timemanagerguicontrol.py", line 20, in 
    from .vectorlayerdialog import VectorLayerDialog  # , AddLayerDialog
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 665, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/imac5k/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/timemanager/vectorlayerdialog.py", line 16, in 
    from future.utils import with_metaclass
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 665, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'future'


Python version: 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 03:03:55) [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] 
QGIS version: 3.2.0-Bonn Bonn, exported 

Python Path:
/Applications/QGIS3.app/Contents/MacOS/../Resources/python
/Users/imac5k/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/imac5k/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
/Applications/QGIS3.app/Contents/MacOS/../Resources/python/plugins
/Library/Frameworks/Python.framework/Versions/3.6/lib/python36.zip
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/lib-dynload
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
/Users/imac5k/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Volumes/Messtechnik/01_Projekt/CH15002_KAGA/10_Geodata_LV95/02_GIS/00_KAGA_Allgemein/180622_KAGA_QGIS3
```

Is there any workaround for this?
Similar issue as: https://github.com/geometalab/Vector-Tiles-Reader-QGIS-Plugin/issues/196

Thanks for advice.

**Comment by anitagraser** [comment]
This has previously been reported in #252

**Comment by soester** [comment]
@anitagraser thanks for the hint!

**Comment by troboukis** [comment]
Hey, I'm still getting the same error (Couldn't load plugin 'timemanager' due to an error when calling its classFactory() method ).
The future module is installed. Any ideas? (have python 3 and qgis 3.6)

**Comment by troboukis** [comment]
The pip3 install future doesn't resolve the issue for me. Unfortunately.

**Comment by wisdomware** [comment]
> The pip3 install future doesn't resolve the issue for me. Unfortunately.

Same issue. I ran the command pip3 install future but it did not fix the issue. I got these errors when I ran this command:
Henrys-Mac-Pro:cesium henry$ pip3 install future
Failed to import the site module
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site.py", line 553, in <module>
    main()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site.py", line 539, in main
    known_paths = addusersitepackages(known_paths)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site.py", line 282, in addusersitepackages
    user_site = getusersitepackages()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site.py", line 258, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site.py", line 248, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/sysconfig.py", line 601, in get_config_var
    return get_config_vars().get(name)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/sysconfig.py", line 580, in get_config_vars
    import _osx_support
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/_osx_support.py", line 4, in <module>
    import re
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/re.py", line 142, in <module>
    class RegexFlag(enum.IntFlag):
AttributeError: module 'enum' has no attribute 'IntFlag'
