### ISSUE TITLE
couldn't load plugin TimeManager on mac 10.14

### ISSUE THREAD

**Issue by rkalasek** [anitagraser/TimeManager#267]
just updated to 3.0.2 and got the following error druing install process:
--------------------------------------
Couldn't load plugin 'timemanager' due to an error when calling its classFactory() method 

ModuleNotFoundError: No module named 'future' 
Traceback (most recent call last):
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 335, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/Users/robert_kalasek/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/timemanager/__init__.py", line 15, in classFactory
    from .timemanager import timemanager
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/robert_kalasek/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/timemanager/timemanager.py", line 26, in 
    from .timemanagercontrol import TimeManagerControl
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/robert_kalasek/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/timemanager/timemanagercontrol.py", line 19, in 
    from .timemanagerguicontrol import TimeManagerGuiControl, MAX_TIME_LENGTH_SECONDS_SLIDER
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/robert_kalasek/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/timemanager/timemanagerguicontrol.py", line 20, in 
    from .vectorlayerdialog import VectorLayerDialog  # , AddLayerDialog
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/robert_kalasek/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/timemanager/vectorlayerdialog.py", line 16, in 
    from future.utils import with_metaclass
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'future'

Python version: 3.6.7 (v3.6.7:6ec5cf24b7, Oct 20 2018, 03:02:14) [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] 
QGIS version: 3.4.1-Madeira Madeira, exported 

Python Path:
/Applications/QGIS3.app/Contents/MacOS/../Resources/python
/Users/robert_kalasek/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/robert_kalasek/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
/Applications/QGIS3.app/Contents/MacOS/../Resources/python/plugins
/Library/Frameworks/SQLite3.framework/Versions/D/Python/3.6
/Library/Frameworks/Python.framework/Versions/3.6/lib/python36.zip
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/lib-dynload
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
/Users/robert_kalasek/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/robert_kalasek/Dropbox/_seglen_myfolder/_events/18_10_1000miles/Tracking/demo

**Comment by anitagraser** [comment]
This has previously been reported in #252
