### ISSUE TITLE
installation /activation fails

### ISSUE THREAD

**Issue by riccardoklinger** [anitagraser/TimeManager#275]
I've installed a fresh QGis 3.4.4 install on MacOS Mojave using python 3.6 Installation of other plugins like Hqgis worked. When I tried to install time manager it says;
Konnte Erweiterung 'timemanager' nicht laden aufgrund eines Fehlers beim Aufruf der classFactory() Methode 

ModuleNotFoundError: No module named 'future' 
Traceback (most recent call last):
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 335, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/Users/ricckli/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/timemanager/__init__.py", line 15, in classFactory
    from .timemanager import timemanager
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/ricckli/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/timemanager/timemanager.py", line 26, in 
    from .timemanagercontrol import TimeManagerControl
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/ricckli/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/timemanager/timemanagercontrol.py", line 19, in 
    from .timemanagerguicontrol import TimeManagerGuiControl, MAX_TIME_LENGTH_SECONDS_SLIDER
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/ricckli/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/timemanager/timemanagerguicontrol.py", line 20, in 
    from .vectorlayerdialog import VectorLayerDialog  # , AddLayerDialog
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/ricckli/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/timemanager/vectorlayerdialog.py", line 16, in 
    from future.utils import with_metaclass
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'future'

Python-Version: 3.6.8 (v3.6.8:3c6b436a57, Dec 24 2018, 02:04:31) [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] 
QGIS-Version: 3.4.4-Madeira Madeira, exported 

Python-Pfad:
/Applications/QGIS3.app/Contents/MacOS/../Resources/python
/Users/ricckli/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/ricckli/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
/Applications/QGIS3.app/Contents/MacOS/../Resources/python/plugins
/Library/Frameworks/SQLite3.framework/Versions/D/Python/3.6
/Library/Frameworks/Python.framework/Versions/3.6/lib/python36.zip
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/lib-dynload
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
/Users/ricckli/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/ricckli/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins

**Comment by riccardoklinger** [comment]
as described in #271 I installed the futre module by hand using 
`pip3 install future` 
in the terminal. You need to have pip3 installed on your mac. pip3 is the pip-version for Python3
