### ISSUE TITLE
WMSTRasterLayer object has no attribute resetSubsetString

### ISSUE THREAD

**Issue by PedroVenancio** [anitagraser/TimeManager#282]
Hi,

Anytime I try to change settings in TimeManager I get:

```
An error has occurred while executing Python code: 

AttributeError: 'WMSTRasterLayer' object has no attribute 'resetSubsetString' 
Traceback (most recent call last):
  File "C:/Users/pedro.venancio/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\timemanager\timemanagercontrol.py", line 271, in showOptionsDialog
    self.loopAnimation)
  File "C:/Users/pedro.venancio/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\timemanager\timemanagerguicontrol.py", line 394, in showOptionsDialog
    settings = layer_settings.getSettingsFromLayer(layer)
  File "C:/Users/pedro.venancio/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\timemanager\layer_settings.py", line 184, in getSettingsFromLayer
    result.resetSubsetString = layer.resetSubsetString()
AttributeError: 'WMSTRasterLayer' object has no attribute 'resetSubsetString'

Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.6.0-Noosa Noosa, af972502ab 
```

To reproduce:
1) Start QGIS;
2) Load a WMS layer (for instance https://landsatlook.usgs.gov/arcgis/services/Sentinel2/ImageServer/WMSServer);
3) Start TimeManager;
4) Configure TimeManager in Settings -> Add Raster -> Start/End Time -> Ok -> Ok;
5) Click again in Settings -> I get the error.

**Comment by anitagraser** [comment]
See #281, please uninstall and reinstall the plugin

**Comment by PedroVenancio** [comment]
Thanks @anitagraser !
