### ISSUE TITLE
Error loading 'time manager'

### ISSUE THREAD

**Issue by troboukis** [anitagraser/TimeManager#296]
Hey, I'm getting the error (Couldn't load plugin 'timemanager' due to an error when calling its classFactory() method ).
The future module is installed. Any ideas? (have python 3 and qgis 3.6)
I've read the older issue but the proposed solution (pip install future) won't resolve the issue for me.

**Comment by anitagraser** [comment]
Related to #258

**Comment by anitagraser** [comment]
Do you get the exact same error message? Are you also using OSX?

I don't have a Mac, so cannot reproduce the issue.

**Comment by troboukis** [comment]
I'm running the Mojave 10.14.5

**Comment by troboukis** [comment]
This is the full error msg I get

--------------

Couldn't load plugin 'timemanager' due to an error when calling its classFactory() method 

ModuleNotFoundError: No module named 'future' 
Traceback (most recent call last):
  File "/Applications/QGIS3.6.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 335, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/Users/viceproduction/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/timemanager/__init__.py", line 16, in classFactory
    from timemanager import timemanager_obj
  File "/Applications/QGIS3.6.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 686, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/viceproduction/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/timemanager/timemanager_obj.py", line 25, in 
    from timemanager.timemanagercontrol import TimeManagerControl
  File "/Applications/QGIS3.6.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 686, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/viceproduction/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/timemanager/timemanagercontrol.py", line 24, in 
    from timemanager.timemanagerguicontrol import TimeManagerGuiControl, MAX_TIME_LENGTH_SECONDS_SLIDER
  File "/Applications/QGIS3.6.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 686, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/viceproduction/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/timemanager/timemanagerguicontrol.py", line 21, in 
    from timemanager.dialogs.vectorlayerdialog import VectorLayerDialog  # , AddLayerDialog
  File "/Applications/QGIS3.6.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 686, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/viceproduction/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/timemanager/dialogs/vectorlayerdialog.py", line 16, in 
    from future.utils import with_metaclass
  File "/Applications/QGIS3.6.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 686, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'future'

**Comment by kannes** [comment]
Maybe drop Python 2 compatibility alltogether, now that QGIS 3 is well mature :)

**Comment by troboukis** [comment]
How do I do that? Sorry but I don't get what you mean...

**Comment by kannes** [comment]
That was directed to @anitagraser not you.

For you the fix is installing the missing (unnecessary) Python package "future". I have no clue about MacOS though and how QGIS on MacOS brings its own Python and how you can access it.

**Comment by openfirmware** [comment]
I ran into this issue too.

QGIS 3.8.0
MacOS High Sierra 10.13

I was able to get the "future" module working by installing using the specific pip version:

```
$ sudo pip3.6 install future
```

The TimeManager plugin appears to be loading now.
