### ISSUE TITLE
Animation showing and files exporting, but "ValueError: strftime format ends with raw % "

### ISSUE THREAD

**Issue by martinpmBD** [anitagraser/TimeManager#307]
Hi,

I am pretty new to Time Manager. I am trying to animate some migrating birds fix: it partially works, but I still get an annoying error message (both on Windows and OSX, with QGIS 3.4.8 and 3.4.7). Even if my time format is "%Y-%m-%d %H:%M:%S" in a string column. So, I don't understand why this message error pop-up. It slow down the processing animation and avoid previsualization.

At the end, I can get the files exported to make an animated GIF. So, I guess there is no a real time format issue if plugin succeed to put the fix in the right sequence... I'm a bit confused.

Thanks for your help!

> ValueError: strftime format ends with raw % 
> Traceback (most recent call last):
>   File "/Users/Martin/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/timemanager/timemanagerguicontrol.py", line 581, in renderLabel
>     labelString = self.labelOptions.getLabel(dt)
>   File "/Users/Martin/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/timemanager/timemanagerguicontrol.py", line 67, in getLabel
>     return time_util.datetime_to_str(dt, self.fmt)
>   File "/Users/Martin/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/timemanager/utils/time_util.py", line 246, in datetime_to_str
>     return datetime.strftime(dt, fmt)
> ValueError: strftime format ends with raw %
> 
> 
> Version de Python : 3.6.6 (v3.6.6:4cf1f54eb7, Jun 26 2018, 19:50:54) [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] 
> Version de QGIS : 3.4.7-Madeira Madeira, exported

**Comment by anitagraser** [comment]
Can you share a test project with data to reproduce this issue?

**Comment by martinpmBD** [comment]
I am simply working with this small shapefile to keep it simple at first.

- "GPS_YYYY-MM-DD_HH:MM:SS" is used as "Start time" and "End time".
- Time frame size = 1 day
- Other parameters as default

[ShapefileText.zip](https://github.com/anitagraser/TimeManager/files/3433071/ShapefileText.zip)

**Comment by anitagraser** [comment]
I cannot reproduce the problem. Please uninstall and reinstall TimeManager and give it another try. 

(Note that the attribute name is truncated to `GPS_YYYY-M` in the Shapefile.)

**Comment by martinpmBD** [comment]
I already tried to uninstall and reinstall several times.

I work on OSX 10.11.6 with Python 3.6.6.

**Comment by anitagraser** [comment]
I've put out calls for other OSX users to try to reproduce this issue

**Comment by mdhyslop** [comment]
I was unable to reproduce the error. OSX 10.13.6 and QGIS 3.6.1-Noosa / Python 3.6.8

**Comment by dieza** [comment]
Couldn't load plugin 'timemanager' due to an error when calling its classFactory() method 

ModuleNotFoundError: No module named 'future' 
Traceback (most recent call last):
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 335, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/Users/agus/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/timemanager/__init__.py", line 16, in classFactory
    from timemanager import timemanager_obj
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/agus/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/timemanager/timemanager_obj.py", line 25, in 
    from timemanager.timemanagercontrol import TimeManagerControl
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/agus/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/timemanager/timemanagercontrol.py", line 24, in 
    from timemanager.timemanagerguicontrol import TimeManagerGuiControl, MAX_TIME_LENGTH_SECONDS_SLIDER
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/agus/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/timemanager/timemanagerguicontrol.py", line 21, in 
    from timemanager.dialogs.vectorlayerdialog import VectorLayerDialog  # , AddLayerDialog
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/agus/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/timemanager/dialogs/vectorlayerdialog.py", line 16, in 
    from future.utils import with_metaclass
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'future'


Python version: 3.6.4 (v3.6.4:d48ecebad5, Dec 18 2017, 21:07:28) [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] 
QGIS version: 3.4.4-Madeira Madeira, exported 

Python Path:
/Applications/QGIS3.app/Contents/MacOS/../Resources/python
/Users/agus/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/agus/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
/Applications/QGIS3.app/Contents/MacOS/../Resources/python/plugins
/Library/Frameworks/SQLite3.framework/Versions/D/Python/3.6
/Library/Frameworks/Python.framework/Versions/3.6/lib/python36.zip
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/lib-dynload
/Users/agus/Library/Python/3.6/lib/python/site-packages
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
/Users/agus/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/agus/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/go2streetview
/Users/agus/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/go2streetview/res
/Users/agus/Library/Python/3.6/lib/python/site-packages/IPython/exten

**Comment by dieza** [comment]
In 3.8 (OSx 10.14.6)
2019-07-28T09:44:02     INFO    Plugin language loaded: ca
2019-07-28T09:44:02     CRITICAL    Translation file {} for lang {} was not loaded properly,falling back to English
2019-07-28T09:44:02     INFO    TimeManager: $Id$ loaded!
2019-07-28T09:44:35     INFO    Time type: IntegerTimestamps
2019-07-28T09:44:36     INFO    Time format: SECONDS FROM EPOCH (float)
2019-07-28T09:44:36     INFO    Layer extents(datetime.datetime(1970, 1, 1, 5, 15, 6), datetime.datetime(1970, 1, 1, 16, 46, 44))

------------

Not Imagemagick
Exception: Imagemagick is not in path. Please install ImageMagick! 
Traceback (most recent call last):
  File "/Users/agus/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/timemanager/timemanagercontrol.py", line 296, in exportVideo
    animate.make_animation(path, delay_millis)
  File "/Users/agus/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/timemanager/animation/animate.py", line 44, in make_animation
    raise Exception("Imagemagick is not in path. Please install ImageMagick!")
Exception: Imagemagick is not in path. Please install ImageMagick!

------------
It seems to me that imagemagick is installed

 convert -version
Version: ImageMagick 7.0.8-56 Q16 x86_64 2019-07-24 https://imagemagick.org
Copyright: © 1999-2019 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules OpenMP(3.1) 
Delegates (built-in): bzlib freetype heic jng jp2 jpeg lcms ltdl lzma openexr png tiff webp xml zlib

$ which convert
/usr/local/bin/convert

**Comment by anitagraser** [comment]
@dieza Thank you for getting involved with this issue. Please note that it would be helpful to stick to the originally reported issue and to open new tickets for other problems you have identified. 

The future issue is already documented in: https://github.com/anitagraser/TimeManager/issues/296

**Comment by jagodki** [comment]
I cannot reproduce the error too (macOS 10.13.6, QGIS 3.4.5, Python 3.6.2)

**Comment by martinpmBD** [comment]
Thanks for your help. Please tell me if I can share your any other information that can give you more clues about this issue.

I will have one more look at it when I will be back on Windows in the next days. Because, as I wrote before, I had the same issue with the same shapefile on Windows.

**Comment by anitagraser** [comment]
Closing for lack of feedback. Reopen if necessary.
