### ISSUE TITLE
Time display options dialog does not open

### ISSUE THREAD

**Issue by anitagraser** [anitagraser/TimeManager#99]
When pressing the button nothing happens. Tested on Win7 with QGIS 2.6.1.

**Comment by carolinux** [comment]
In Ubuntu 14.04 that I'm using it works. On Mavericks OSX it actually threw an exception "no module named qgscolorbutton". Need to investigate.

**Comment by carolinux** [comment]
OK, so on my Windows virtual machine it also can't find the qgscolorbutton module and throws an exception.
It's strange @anitagraser that for you it doesn't show an error..

**Comment by anitagraser** [comment]
On my Win8 machine, I do get the qcolordialog error. Anyway, still needs fixing :-)

**Comment by riggsd** [comment]
Homebrew QGIS 2.6.1 on Mac OS X 10.9.4.


```
Traceback (most recent call last):
  File "/Users/driggs/.qgis2/python/plugins/timemanager/timemanagerguicontrol.py", line 109, in showLabelOptions
    self.labelOptionsDialog = uic.loadUi(os.path.join(path,LABEL_WIDGET_FILE ))
  File "/usr/local/lib/python2.7/site-packages/PyQt4/uic/__init__.py", line 238, in loadUi
    return DynamicUILoader(package).loadUi(uifile, baseinstance, resource_suffix)
  File "/usr/local/lib/python2.7/site-packages/PyQt4/uic/Loader/loader.py", line 71, in loadUi
    return self.parse(filename, resource_suffix, basedir)
  File "/usr/local/lib/python2.7/site-packages/PyQt4/uic/uiparser.py", line 978, in parse
    actor(elem)
  File "/usr/local/lib/python2.7/site-packages/PyQt4/uic/uiparser.py", line 804, in createUserInterface
    self.traverseWidgetTree(elem)
  File "/usr/local/lib/python2.7/site-packages/PyQt4/uic/uiparser.py", line 782, in traverseWidgetTree
    handler(self, child)
  File "/usr/local/lib/python2.7/site-packages/PyQt4/uic/uiparser.py", line 253, in createWidget
    self.traverseWidgetTree(elem)
  File "/usr/local/lib/python2.7/site-packages/PyQt4/uic/uiparser.py", line 782, in traverseWidgetTree
    handler(self, child)
  File "/usr/local/lib/python2.7/site-packages/PyQt4/uic/uiparser.py", line 493, in createLayout
    self.traverseWidgetTree(elem)
  File "/usr/local/lib/python2.7/site-packages/PyQt4/uic/uiparser.py", line 782, in traverseWidgetTree
    handler(self, child)
  File "/usr/local/lib/python2.7/site-packages/PyQt4/uic/uiparser.py", line 536, in handleItem
    self.traverseWidgetTree(elem)
  File "/usr/local/lib/python2.7/site-packages/PyQt4/uic/uiparser.py", line 782, in traverseWidgetTree
    handler(self, child)
  File "/usr/local/lib/python2.7/site-packages/PyQt4/uic/uiparser.py", line 493, in createLayout
    self.traverseWidgetTree(elem)
  File "/usr/local/lib/python2.7/site-packages/PyQt4/uic/uiparser.py", line 782, in traverseWidgetTree
    handler(self, child)
  File "/usr/local/lib/python2.7/site-packages/PyQt4/uic/uiparser.py", line 536, in handleItem
    self.traverseWidgetTree(elem)
  File "/usr/local/lib/python2.7/site-packages/PyQt4/uic/uiparser.py", line 782, in traverseWidgetTree
    handler(self, child)
  File "/usr/local/lib/python2.7/site-packages/PyQt4/uic/uiparser.py", line 493, in createLayout
    self.traverseWidgetTree(elem)
  File "/usr/local/lib/python2.7/site-packages/PyQt4/uic/uiparser.py", line 782, in traverseWidgetTree
    handler(self, child)
  File "/usr/local/lib/python2.7/site-packages/PyQt4/uic/uiparser.py", line 536, in handleItem
    self.traverseWidgetTree(elem)
  File "/usr/local/lib/python2.7/site-packages/PyQt4/uic/uiparser.py", line 782, in traverseWidgetTree
    handler(self, child)
  File "/usr/local/lib/python2.7/site-packages/PyQt4/uic/uiparser.py", line 244, in createWidget
    self.stack.push(self.setupObject(widget_class, parent, elem))
  File "/usr/local/lib/python2.7/site-packages/PyQt4/uic/uiparser.py", line 205, in setupObject
    obj =  self.factory.createQObject(clsname, name, args, is_attribute)
  File "/usr/local/lib/python2.7/site-packages/PyQt4/uic/objcreator.py", line 106, in createQObject
    factory = self.findQObjectType(classname)
  File "/usr/local/lib/python2.7/site-packages/PyQt4/uic/objcreator.py", line 131, in findQObjectType
    w = module.search(classname)
  File "/usr/local/lib/python2.7/site-packages/PyQt4/uic/Loader/qobjectcreator.py", line 107, in search
    module = __import__(mname, {}, {}, (cls,))
  File "/usr/local/Cellar/qgis-26/2.6.1/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 460, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: No module named qgscolorbutton
```

**Comment by carolinux** [comment]
Try current master!
0102ea551b29

Works on my OSX Mavericks
http://imgur.com/BC6om0y

**Comment by carolinux** [comment]
version 1.5.2 has support for this
